### ISSUE TITLE
Weiter lösungen

### ISSUE THREAD

**Issue by musdasch** [CoalaJoe/OOP1#2]
Ich bin auch dabei meine Lösungen auf github zu stelle ich habe dich in meinem README erwend fals es dich nicht stört. [Repo](https://github.com/musdasch/PG-HF-ICT)

**Comment by CoalaJoe** [comment]
Danke. Ich werde dein Repo bei mir auch hinzufügen.

**Comment by musdasch** [comment]
Super danke :-)
