### ISSUE TITLE
Aufgabe 12 - Caesar Chiffre

### ISSUE THREAD

**Issue by musdasch** [CoalaJoe/OOP1#3]
Hi @CoalaJoe 
Du hast noch einen Fehler in deinem Ceasar Chiffre Programm. Sobald das Programm bei "z" ankommt wird nicht "a" angezeigt sondern ein Zeichen weiter oben in der ASCII Tabelle das hat zur folge das der String nicht richtig chiffriert wird. Du kannst Modulo verwenden.

**Comment by CoalaJoe** [comment]
Danke für den Hinweis.
